### ISSUE TITLE
Validator method breaks other fields

### ISSUE THREAD

**Issue by AshPowell** [Askedio/laravel-profanity-filter#13]
I'm using it like this and get an error that the next required field is required, it's definitely there in the post and only happens with |profanity as a validation rule.

```
$validator = Validator::make(request()->all(), [
            'title'          => 'required|profanity',
            'phone'     => 'required|max:10'
        ]);

  if ($validator->fails()) {
            return response()->json([
                'msg' => $validator->messages()->first(),
            ], 400);
        }
```

Even though I'm submitting all the correct information, validator is failing and returning that the phone field is required.

Im assuming this is due to the request being replaced, is there a way to get the rule to just return true/false when used in this way?

Thanks

**Comment by gcphost** [comment]
Hi @AshPowell 

Sorry for the delay to a response. I have just merged a PR that fixes the issue you are having, it is tagged as the latest release. 

You can see more details here:
https://github.com/Askedio/laravel-profanity-filter/pull/14
