### ISSUE TITLE
validation.profanity changeable ?

### ISSUE THREAD

**Issue by Niush** [Askedio/laravel-profanity-filter#16]
Can't we change "validation.profanity" error message to something custom output during the Laravel Validation. i.e. during the $request->validate()

**Comment by HossamHoussien** [comment]
If you're using Laravel then yes you can. Go to `resources\lang\en\validation.php` scroll down into the file until you hit "custom" section and add a new rule like below

    `'custom' => [

        '*' => [

            'profanity' => 'NOOOO', // Replace this with whatever you want

        ],

    ],`
